# Generated by Django 6.0.2 on 2026-03-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0002_systemconfig_employee_face_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("hr", "HR"), ("employee", "Employee")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
