# Generated by Django 6.0.3 on 2026-04-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_payroll_lop_amount_payroll_lop_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='month',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
